//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inc.TeamAssistant.WebUI.Features.Meta {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MetaResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetaResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Inc.TeamAssistant.WebUI.Features.Meta.MetaResources", typeof(MetaResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        internal static string AppraiserDescription {
            get {
                return ResourceManager.GetString("AppraiserDescription", resourceCulture);
            }
        }
        
        internal static string AppraiserKeywords {
            get {
                return ResourceManager.GetString("AppraiserKeywords", resourceCulture);
            }
        }
        
        internal static string CheckInDescription {
            get {
                return ResourceManager.GetString("CheckInDescription", resourceCulture);
            }
        }
        
        internal static string CheckInKeywords {
            get {
                return ResourceManager.GetString("CheckInKeywords", resourceCulture);
            }
        }
        
        internal static string MainDescription {
            get {
                return ResourceManager.GetString("MainDescription", resourceCulture);
            }
        }
        
        internal static string MainKeywords {
            get {
                return ResourceManager.GetString("MainKeywords", resourceCulture);
            }
        }
        
        internal static string AppraiserTitle {
            get {
                return ResourceManager.GetString("AppraiserTitle", resourceCulture);
            }
        }
        
        internal static string CheckInTitle {
            get {
                return ResourceManager.GetString("CheckInTitle", resourceCulture);
            }
        }
        
        internal static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        internal static string OgAppraiserTitle {
            get {
                return ResourceManager.GetString("OgAppraiserTitle", resourceCulture);
            }
        }
        
        internal static string OgAppraiserDescription {
            get {
                return ResourceManager.GetString("OgAppraiserDescription", resourceCulture);
            }
        }
        
        internal static string OgAppraiserImageText {
            get {
                return ResourceManager.GetString("OgAppraiserImageText", resourceCulture);
            }
        }
        
        internal static string OgCheckInTitle {
            get {
                return ResourceManager.GetString("OgCheckInTitle", resourceCulture);
            }
        }
        
        internal static string OgCheckInDescription {
            get {
                return ResourceManager.GetString("OgCheckInDescription", resourceCulture);
            }
        }
        
        internal static string OgCheckInImageText {
            get {
                return ResourceManager.GetString("OgCheckInImageText", resourceCulture);
            }
        }
        
        internal static string OgMainTitle {
            get {
                return ResourceManager.GetString("OgMainTitle", resourceCulture);
            }
        }
        
        internal static string OgMainDescription {
            get {
                return ResourceManager.GetString("OgMainDescription", resourceCulture);
            }
        }
        
        internal static string OgMainImageText {
            get {
                return ResourceManager.GetString("OgMainImageText", resourceCulture);
            }
        }
    }
}
