//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inc.TeamAssistant.WebUI.Features.Main {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Inc.TeamAssistant.WebUI.Features.Main.MainResources", typeof(MainResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string VideoNotSupported {
            get {
                return ResourceManager.GetString("VideoNotSupported", resourceCulture);
            }
        }
        
        internal static string MainHeader {
            get {
                return ResourceManager.GetString("MainHeader", resourceCulture);
            }
        }
        
        internal static string MainSubHeader {
            get {
                return ResourceManager.GetString("MainSubHeader", resourceCulture);
            }
        }
        
        internal static string ToolAppraiser {
            get {
                return ResourceManager.GetString("ToolAppraiser", resourceCulture);
            }
        }
        
        internal static string ToolReviewer {
            get {
                return ResourceManager.GetString("ToolReviewer", resourceCulture);
            }
        }
        
        internal static string ToolRandomCoffee {
            get {
                return ResourceManager.GetString("ToolRandomCoffee", resourceCulture);
            }
        }
        
        internal static string ToolCheckIn {
            get {
                return ResourceManager.GetString("ToolCheckIn", resourceCulture);
            }
        }
        
        internal static string CreateBotLink {
            get {
                return ResourceManager.GetString("CreateBotLink", resourceCulture);
            }
        }
    }
}
