//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inc.TeamAssistant.WebUI.Features.RoomProperties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RoomPropertiesResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoomPropertiesResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Inc.TeamAssistant.WebUI.Features.RoomProperties.RoomPropertiesResources", typeof(RoomPropertiesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string RetroPropertiesSectionTitle {
            get {
                return ResourceManager.GetString("RetroPropertiesSectionTitle", resourceCulture);
            }
        }
        
        internal static string RetroPropertiesSectionHelp {
            get {
                return ResourceManager.GetString("RetroPropertiesSectionHelp", resourceCulture);
            }
        }
        
        internal static string RetroTemplateField {
            get {
                return ResourceManager.GetString("RetroTemplateField", resourceCulture);
            }
        }
        
        internal static string RetroTypeField {
            get {
                return ResourceManager.GetString("RetroTypeField", resourceCulture);
            }
        }
        
        internal static string TimerDurationField {
            get {
                return ResourceManager.GetString("TimerDurationField", resourceCulture);
            }
        }
        
        internal static string TimerDurationTemplate {
            get {
                return ResourceManager.GetString("TimerDurationTemplate", resourceCulture);
            }
        }
        
        internal static string VotePropertiesSectionTitle {
            get {
                return ResourceManager.GetString("VotePropertiesSectionTitle", resourceCulture);
            }
        }
        
        internal static string VotePropertiesSectionHelp {
            get {
                return ResourceManager.GetString("VotePropertiesSectionHelp", resourceCulture);
            }
        }
        
        internal static string VoteCountField {
            get {
                return ResourceManager.GetString("VoteCountField", resourceCulture);
            }
        }
        
        internal static string VoteByItemCountField {
            get {
                return ResourceManager.GetString("VoteByItemCountField", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string RetroTypeClosed {
            get {
                return ResourceManager.GetString("RetroTypeClosed", resourceCulture);
            }
        }
        
        internal static string RetroTypeOpened {
            get {
                return ResourceManager.GetString("RetroTypeOpened", resourceCulture);
            }
        }
        
        internal static string RetroTypeHidden {
            get {
                return ResourceManager.GetString("RetroTypeHidden", resourceCulture);
            }
        }
        
        internal static string SurveyPropertiesSectionTitle {
            get {
                return ResourceManager.GetString("SurveyPropertiesSectionTitle", resourceCulture);
            }
        }
        
        internal static string SurveyPropertiesSectionHelp {
            get {
                return ResourceManager.GetString("SurveyPropertiesSectionHelp", resourceCulture);
            }
        }
        
        internal static string SurveyTemplateField {
            get {
                return ResourceManager.GetString("SurveyTemplateField", resourceCulture);
            }
        }
        
        internal static string TemplateStartStopContinue {
            get {
                return ResourceManager.GetString("TemplateStartStopContinue", resourceCulture);
            }
        }
        
        internal static string TemplateToDiscussDiscussingDiscussed {
            get {
                return ResourceManager.GetString("TemplateToDiscussDiscussingDiscussed", resourceCulture);
            }
        }
        
        internal static string SurveyTemplateSpotifyHealthCheck {
            get {
                return ResourceManager.GetString("SurveyTemplateSpotifyHealthCheck", resourceCulture);
            }
        }
        
        internal static string SurveyTemplateRemoteTeamHappiness {
            get {
                return ResourceManager.GetString("SurveyTemplateRemoteTeamHappiness", resourceCulture);
            }
        }
        
        internal static string TeamHealthCheck {
            get {
                return ResourceManager.GetString("TeamHealthCheck", resourceCulture);
            }
        }
        
        internal static string RetroBoard {
            get {
                return ResourceManager.GetString("RetroBoard", resourceCulture);
            }
        }
        
        internal static string RetroBacklog {
            get {
                return ResourceManager.GetString("RetroBacklog", resourceCulture);
            }
        }
        
        internal static string FinishHint {
            get {
                return ResourceManager.GetString("FinishHint", resourceCulture);
            }
        }
        
        internal static string RaiseHandHint {
            get {
                return ResourceManager.GetString("RaiseHandHint", resourceCulture);
            }
        }
        
        internal static string TimerStartHint {
            get {
                return ResourceManager.GetString("TimerStartHint", resourceCulture);
            }
        }
        
        internal static string RoomPropertiesHint {
            get {
                return ResourceManager.GetString("RoomPropertiesHint", resourceCulture);
            }
        }
        
        internal static string PreviousHint {
            get {
                return ResourceManager.GetString("PreviousHint", resourceCulture);
            }
        }
        
        internal static string NextHint {
            get {
                return ResourceManager.GetString("NextHint", resourceCulture);
            }
        }
        
        internal static string GiveFacilitatorHint {
            get {
                return ResourceManager.GetString("GiveFacilitatorHint", resourceCulture);
            }
        }
        
        internal static string TimerStart {
            get {
                return ResourceManager.GetString("TimerStart", resourceCulture);
            }
        }
        
        internal static string ConfirmGiveFacilitator {
            get {
                return ResourceManager.GetString("ConfirmGiveFacilitator", resourceCulture);
            }
        }
        
        internal static string VotesCount {
            get {
                return ResourceManager.GetString("VotesCount", resourceCulture);
            }
        }
        
        internal static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        internal static string LowerHandHint {
            get {
                return ResourceManager.GetString("LowerHandHint", resourceCulture);
            }
        }
        
        internal static string RoomHistory {
            get {
                return ResourceManager.GetString("RoomHistory", resourceCulture);
            }
        }
    }
}
