//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inc.TeamAssistant.WebUI.Features.Dashboard {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DashboardResources_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardResources_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Inc.TeamAssistant.WebUI.Features.Dashboard.DashboardResources_ru", typeof(DashboardResources_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BooleanTrueText {
            get {
                return ResourceManager.GetString("BooleanTrueText", resourceCulture);
            }
        }
        
        internal static string BooleanFalseText {
            get {
                return ResourceManager.GetString("BooleanFalseText", resourceCulture);
            }
        }
        
        internal static string AppraiserHistoryTitle {
            get {
                return ResourceManager.GetString("AppraiserHistoryTitle", resourceCulture);
            }
        }
        
        internal static string AssessmentDate {
            get {
                return ResourceManager.GetString("AssessmentDate", resourceCulture);
            }
        }
        
        internal static string TotalStories {
            get {
                return ResourceManager.GetString("TotalStories", resourceCulture);
            }
        }
        
        internal static string AssessmentSum {
            get {
                return ResourceManager.GetString("AssessmentSum", resourceCulture);
            }
        }
        
        internal static string GoToCurrentSessionButtonText {
            get {
                return ResourceManager.GetString("GoToCurrentSessionButtonText", resourceCulture);
            }
        }
        
        internal static string AppraiserIntegrationConfirmText {
            get {
                return ResourceManager.GetString("AppraiserIntegrationConfirmText", resourceCulture);
            }
        }
        
        internal static string AppraiserIntegrationTitle {
            get {
                return ResourceManager.GetString("AppraiserIntegrationTitle", resourceCulture);
            }
        }
        
        internal static string AppraiserIntegrationAccessTokenLabel {
            get {
                return ResourceManager.GetString("AppraiserIntegrationAccessTokenLabel", resourceCulture);
            }
        }
        
        internal static string AppraiserIntegrationProjectKeyLabel {
            get {
                return ResourceManager.GetString("AppraiserIntegrationProjectKeyLabel", resourceCulture);
            }
        }
        
        internal static string AppraiserIntegrationScrumMasterLabel {
            get {
                return ResourceManager.GetString("AppraiserIntegrationScrumMasterLabel", resourceCulture);
            }
        }
        
        internal static string AppraiserIntegrationSaveButton {
            get {
                return ResourceManager.GetString("AppraiserIntegrationSaveButton", resourceCulture);
            }
        }
        
        internal static string AppraiserIntegrationDisableButton {
            get {
                return ResourceManager.GetString("AppraiserIntegrationDisableButton", resourceCulture);
            }
        }
        
        internal static string AppraiserIntegrationEnableButton {
            get {
                return ResourceManager.GetString("AppraiserIntegrationEnableButton", resourceCulture);
            }
        }
        
        internal static string AppraiserIntegrationEnableSuccess {
            get {
                return ResourceManager.GetString("AppraiserIntegrationEnableSuccess", resourceCulture);
            }
        }
        
        internal static string CheckInMoveToMapTitle {
            get {
                return ResourceManager.GetString("CheckInMoveToMapTitle", resourceCulture);
            }
        }
        
        internal static string CheckInMapWidgetTitle {
            get {
                return ResourceManager.GetString("CheckInMapWidgetTitle", resourceCulture);
            }
        }
        
        internal static string RandomCoffeeHistoryWidgetTitle {
            get {
                return ResourceManager.GetString("RandomCoffeeHistoryWidgetTitle", resourceCulture);
            }
        }
        
        internal static string RandomCoffeeFirstTitle {
            get {
                return ResourceManager.GetString("RandomCoffeeFirstTitle", resourceCulture);
            }
        }
        
        internal static string RandomCoffeeSecondTitle {
            get {
                return ResourceManager.GetString("RandomCoffeeSecondTitle", resourceCulture);
            }
        }
        
        internal static string RandomCoffeeNoPair {
            get {
                return ResourceManager.GetString("RandomCoffeeNoPair", resourceCulture);
            }
        }
        
        internal static string ReviewAverageStatsWidgetTitle {
            get {
                return ResourceManager.GetString("ReviewAverageStatsWidgetTitle", resourceCulture);
            }
        }
        
        internal static string ReviewAverageStatsTitle {
            get {
                return ResourceManager.GetString("ReviewAverageStatsTitle", resourceCulture);
            }
        }
        
        internal static string ReviewAverageFirstTouch {
            get {
                return ResourceManager.GetString("ReviewAverageFirstTouch", resourceCulture);
            }
        }
        
        internal static string ReviewAverageReview {
            get {
                return ResourceManager.GetString("ReviewAverageReview", resourceCulture);
            }
        }
        
        internal static string ReviewAverageCorrection {
            get {
                return ResourceManager.GetString("ReviewAverageCorrection", resourceCulture);
            }
        }
        
        internal static string LastTasksWidgetTitle {
            get {
                return ResourceManager.GetString("LastTasksWidgetTitle", resourceCulture);
            }
        }
        
        internal static string ReviewOwnerNameTitle {
            get {
                return ResourceManager.GetString("ReviewOwnerNameTitle", resourceCulture);
            }
        }
        
        internal static string ReviewDescriptionTitle {
            get {
                return ResourceManager.GetString("ReviewDescriptionTitle", resourceCulture);
            }
        }
        
        internal static string ReviewReviewerNameTitle {
            get {
                return ResourceManager.GetString("ReviewReviewerNameTitle", resourceCulture);
            }
        }
        
        internal static string ReviewStateTitle {
            get {
                return ResourceManager.GetString("ReviewStateTitle", resourceCulture);
            }
        }
        
        internal static string ReviewStats {
            get {
                return ResourceManager.GetString("ReviewStats", resourceCulture);
            }
        }
        
        internal static string TaskForReviewStateFirstAccept {
            get {
                return ResourceManager.GetString("TaskForReviewStateFirstAccept", resourceCulture);
            }
        }
        
        internal static string TaskForReviewStateNew {
            get {
                return ResourceManager.GetString("TaskForReviewStateNew", resourceCulture);
            }
        }
        
        internal static string TaskForReviewStateInProgress {
            get {
                return ResourceManager.GetString("TaskForReviewStateInProgress", resourceCulture);
            }
        }
        
        internal static string TaskForReviewStateOnCorrection {
            get {
                return ResourceManager.GetString("TaskForReviewStateOnCorrection", resourceCulture);
            }
        }
        
        internal static string TaskForReviewStateAccept {
            get {
                return ResourceManager.GetString("TaskForReviewStateAccept", resourceCulture);
            }
        }
        
        internal static string HasConcreteReviewer {
            get {
                return ResourceManager.GetString("HasConcreteReviewer", resourceCulture);
            }
        }
        
        internal static string HasReassign {
            get {
                return ResourceManager.GetString("HasReassign", resourceCulture);
            }
        }
        
        internal static string FirstTouch {
            get {
                return ResourceManager.GetString("FirstTouch", resourceCulture);
            }
        }
        
        internal static string FirstTouchHelp {
            get {
                return ResourceManager.GetString("FirstTouchHelp", resourceCulture);
            }
        }
        
        internal static string Correction {
            get {
                return ResourceManager.GetString("Correction", resourceCulture);
            }
        }
        
        internal static string CorrectionHelp {
            get {
                return ResourceManager.GetString("CorrectionHelp", resourceCulture);
            }
        }
        
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        internal static string ReviewHelp {
            get {
                return ResourceManager.GetString("ReviewHelp", resourceCulture);
            }
        }
        
        internal static string ReviewTotalStatsWidgetTitle {
            get {
                return ResourceManager.GetString("ReviewTotalStatsWidgetTitle", resourceCulture);
            }
        }
        
        internal static string ReviewByReviewerTemplate {
            get {
                return ResourceManager.GetString("ReviewByReviewerTemplate", resourceCulture);
            }
        }
        
        internal static string ReviewByOwnerTemplate {
            get {
                return ResourceManager.GetString("ReviewByOwnerTemplate", resourceCulture);
            }
        }
        
        internal static string ConfirmDeleteTeammate {
            get {
                return ResourceManager.GetString("ConfirmDeleteTeammate", resourceCulture);
            }
        }
        
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string RecoveryTeammate {
            get {
                return ResourceManager.GetString("RecoveryTeammate", resourceCulture);
            }
        }
        
        internal static string TeammatesWidgetTitle {
            get {
                return ResourceManager.GetString("TeammatesWidgetTitle", resourceCulture);
            }
        }
        
        internal static string PersonName {
            get {
                return ResourceManager.GetString("PersonName", resourceCulture);
            }
        }
        
        internal static string LeaveUntil {
            get {
                return ResourceManager.GetString("LeaveUntil", resourceCulture);
            }
        }
        
        internal static string ExcludeFromTeam {
            get {
                return ResourceManager.GetString("ExcludeFromTeam", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        internal static string DisableWidgetHelpTemplate {
            get {
                return ResourceManager.GetString("DisableWidgetHelpTemplate", resourceCulture);
            }
        }
        
        internal static string SettingsApplied {
            get {
                return ResourceManager.GetString("SettingsApplied", resourceCulture);
            }
        }
        
        internal static string BotWidgetTitle {
            get {
                return ResourceManager.GetString("BotWidgetTitle", resourceCulture);
            }
        }
        
        internal static string SelectTeam {
            get {
                return ResourceManager.GetString("SelectTeam", resourceCulture);
            }
        }
        
        internal static string CreateBot {
            get {
                return ResourceManager.GetString("CreateBot", resourceCulture);
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string ConnectToTeamHelp {
            get {
                return ResourceManager.GetString("ConnectToTeamHelp", resourceCulture);
            }
        }
        
        internal static string ConnectToTeamButton {
            get {
                return ResourceManager.GetString("ConnectToTeamButton", resourceCulture);
            }
        }
        
        internal static string SelectTeamTitle {
            get {
                return ResourceManager.GetString("SelectTeamTitle", resourceCulture);
            }
        }
        
        internal static string BotField {
            get {
                return ResourceManager.GetString("BotField", resourceCulture);
            }
        }
        
        internal static string TeamField {
            get {
                return ResourceManager.GetString("TeamField", resourceCulture);
            }
        }
        
        internal static string TaskForReviewStateAcceptWithComments {
            get {
                return ResourceManager.GetString("TaskForReviewStateAcceptWithComments", resourceCulture);
            }
        }
        
        internal static string CanFinalize {
            get {
                return ResourceManager.GetString("CanFinalize", resourceCulture);
            }
        }
    }
}
