FROM nginx:1.23.1

ARG PROJECT
EXPOSE 80

# VARS
ENV APP_DIR="/usr/share/nginx/html"

COPY ./output/${PROJECT}/wwwroot ${APP_DIR}
COPY ./cicd/nginx_static.conf /etc/nginx/nginx.conf
WORKDIR ${APP_DIR}