//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inc.TeamAssistant.WebUI.Features.Layouts {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LayoutResources_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LayoutResources_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Inc.TeamAssistant.WebUI.Features.Layouts.LayoutResources_ru", typeof(LayoutResources_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string LinkMain {
            get {
                return ResourceManager.GetString("LinkMain", resourceCulture);
            }
        }
        
        internal static string GroupNavigation {
            get {
                return ResourceManager.GetString("GroupNavigation", resourceCulture);
            }
        }
        
        internal static string LinkConstructor {
            get {
                return ResourceManager.GetString("LinkConstructor", resourceCulture);
            }
        }
        
        internal static string LinkDashboard {
            get {
                return ResourceManager.GetString("LinkDashboard", resourceCulture);
            }
        }
        
        internal static string GroupTech {
            get {
                return ResourceManager.GetString("GroupTech", resourceCulture);
            }
        }
        
        internal static string GroupStorage {
            get {
                return ResourceManager.GetString("GroupStorage", resourceCulture);
            }
        }
        
        internal static string GroupTools {
            get {
                return ResourceManager.GetString("GroupTools", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string AcceptCookieText {
            get {
                return ResourceManager.GetString("AcceptCookieText", resourceCulture);
            }
        }
        
        internal static string AcceptCookieButton {
            get {
                return ResourceManager.GetString("AcceptCookieButton", resourceCulture);
            }
        }
        
        internal static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
    }
}
