//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inc.TeamAssistant.WebUI.Features.Retro {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RetroResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RetroResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Inc.TeamAssistant.WebUI.Features.Retro.RetroResources", typeof(RetroResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static string CollectingText {
            get {
                return ResourceManager.GetString("CollectingText", resourceCulture);
            }
        }
        
        internal static string GroupingText {
            get {
                return ResourceManager.GetString("GroupingText", resourceCulture);
            }
        }
        
        internal static string PrioritizingText {
            get {
                return ResourceManager.GetString("PrioritizingText", resourceCulture);
            }
        }
        
        internal static string ConnectionStateConnecting {
            get {
                return ResourceManager.GetString("ConnectionStateConnecting", resourceCulture);
            }
        }
        
        internal static string Reconnect {
            get {
                return ResourceManager.GetString("Reconnect", resourceCulture);
            }
        }
        
        internal static string ConfirmMoveToDiscussing {
            get {
                return ResourceManager.GetString("ConfirmMoveToDiscussing", resourceCulture);
            }
        }
        
        internal static string DiscussingText {
            get {
                return ResourceManager.GetString("DiscussingText", resourceCulture);
            }
        }
        
        internal static string CollectingTitle {
            get {
                return ResourceManager.GetString("CollectingTitle", resourceCulture);
            }
        }
        
        internal static string GroupingTitle {
            get {
                return ResourceManager.GetString("GroupingTitle", resourceCulture);
            }
        }
        
        internal static string PrioritizingTitle {
            get {
                return ResourceManager.GetString("PrioritizingTitle", resourceCulture);
            }
        }
        
        internal static string DiscussingTitle {
            get {
                return ResourceManager.GetString("DiscussingTitle", resourceCulture);
            }
        }
        
        internal static string SlotDropText {
            get {
                return ResourceManager.GetString("SlotDropText", resourceCulture);
            }
        }
        
        internal static string NextHint {
            get {
                return ResourceManager.GetString("NextHint", resourceCulture);
            }
        }
        
        internal static string ItemRemoveConfirm {
            get {
                return ResourceManager.GetString("ItemRemoveConfirm", resourceCulture);
            }
        }
        
        internal static string PreviousHint {
            get {
                return ResourceManager.GetString("PreviousHint", resourceCulture);
            }
        }
        
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        internal static string ActionItemStageNewTitle {
            get {
                return ResourceManager.GetString("ActionItemStageNewTitle", resourceCulture);
            }
        }
        
        internal static string ActionItemStageDoneTitle {
            get {
                return ResourceManager.GetString("ActionItemStageDoneTitle", resourceCulture);
            }
        }
        
        internal static string TimerStart {
            get {
                return ResourceManager.GetString("TimerStart", resourceCulture);
            }
        }
        
        internal static string TimerStop {
            get {
                return ResourceManager.GetString("TimerStop", resourceCulture);
            }
        }
        
        internal static string TimerStartHint {
            get {
                return ResourceManager.GetString("TimerStartHint", resourceCulture);
            }
        }
        
        internal static string FinishHint {
            get {
                return ResourceManager.GetString("FinishHint", resourceCulture);
            }
        }
        
        internal static string ConfirmGiveFacilitator {
            get {
                return ResourceManager.GetString("ConfirmGiveFacilitator", resourceCulture);
            }
        }
        
        internal static string GiveFacilitatorHint {
            get {
                return ResourceManager.GetString("GiveFacilitatorHint", resourceCulture);
            }
        }
        
        internal static string RaiseHandHint {
            get {
                return ResourceManager.GetString("RaiseHandHint", resourceCulture);
            }
        }
        
        internal static string LowerHandHint {
            get {
                return ResourceManager.GetString("LowerHandHint", resourceCulture);
            }
        }
        
        internal static string RetroAssessmentTitle {
            get {
                return ResourceManager.GetString("RetroAssessmentTitle", resourceCulture);
            }
        }
        
        internal static string RetroAssessmentQuestion {
            get {
                return ResourceManager.GetString("RetroAssessmentQuestion", resourceCulture);
            }
        }
        
        internal static string RetroAssessmentValueHint {
            get {
                return ResourceManager.GetString("RetroAssessmentValueHint", resourceCulture);
            }
        }
        
        internal static string AssessmentSuccess {
            get {
                return ResourceManager.GetString("AssessmentSuccess", resourceCulture);
            }
        }
        
        internal static string ColumnStartTitle {
            get {
                return ResourceManager.GetString("ColumnStartTitle", resourceCulture);
            }
        }
        
        internal static string ColumnStopTitle {
            get {
                return ResourceManager.GetString("ColumnStopTitle", resourceCulture);
            }
        }
        
        internal static string ColumnContinueTitle {
            get {
                return ResourceManager.GetString("ColumnContinueTitle", resourceCulture);
            }
        }
        
        internal static string ColumnStartDescription {
            get {
                return ResourceManager.GetString("ColumnStartDescription", resourceCulture);
            }
        }
        
        internal static string ColumnStopDescription {
            get {
                return ResourceManager.GetString("ColumnStopDescription", resourceCulture);
            }
        }
        
        internal static string ColumnContinueDescription {
            get {
                return ResourceManager.GetString("ColumnContinueDescription", resourceCulture);
            }
        }
        
        internal static string ColumnToDiscussTitle {
            get {
                return ResourceManager.GetString("ColumnToDiscussTitle", resourceCulture);
            }
        }
        
        internal static string ColumnDiscussingTitle {
            get {
                return ResourceManager.GetString("ColumnDiscussingTitle", resourceCulture);
            }
        }
        
        internal static string ColumnDiscussedTitle {
            get {
                return ResourceManager.GetString("ColumnDiscussedTitle", resourceCulture);
            }
        }
        
        internal static string ColumnToDiscussDescription {
            get {
                return ResourceManager.GetString("ColumnToDiscussDescription", resourceCulture);
            }
        }
        
        internal static string ColumnDiscussingDescription {
            get {
                return ResourceManager.GetString("ColumnDiscussingDescription", resourceCulture);
            }
        }
        
        internal static string ColumnDiscussedDescription {
            get {
                return ResourceManager.GetString("ColumnDiscussedDescription", resourceCulture);
            }
        }
        
        internal static string RetroPropertiesHint {
            get {
                return ResourceManager.GetString("RetroPropertiesHint", resourceCulture);
            }
        }
        
        internal static string RetroProperties {
            get {
                return ResourceManager.GetString("RetroProperties", resourceCulture);
            }
        }
        
        internal static string BacklogText {
            get {
                return ResourceManager.GetString("BacklogText", resourceCulture);
            }
        }
        
        internal static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        internal static string ActionsHint {
            get {
                return ResourceManager.GetString("ActionsHint", resourceCulture);
            }
        }
        
        internal static string ActionItemStageDoneHint {
            get {
                return ResourceManager.GetString("ActionItemStageDoneHint", resourceCulture);
            }
        }
        
        internal static string ActionItemStageNewHint {
            get {
                return ResourceManager.GetString("ActionItemStageNewHint", resourceCulture);
            }
        }
        
        internal static string CanNotStartRetro {
            get {
                return ResourceManager.GetString("CanNotStartRetro", resourceCulture);
            }
        }
        
        internal static string ConnectionStateLost {
            get {
                return ResourceManager.GetString("ConnectionStateLost", resourceCulture);
            }
        }
        
        internal static string VotesCount {
            get {
                return ResourceManager.GetString("VotesCount", resourceCulture);
            }
        }
        
        internal static string ActionItemStagePinnedTitle {
            get {
                return ResourceManager.GetString("ActionItemStagePinnedTitle", resourceCulture);
            }
        }
        
        internal static string ActionItemStagePinnedHint {
            get {
                return ResourceManager.GetString("ActionItemStagePinnedHint", resourceCulture);
            }
        }
        
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
    }
}
