//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inc.TeamAssistant.WebUI.Features.Retro {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RetroResources_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RetroResources_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Inc.TeamAssistant.WebUI.Features.Retro.RetroResources_ru", typeof(RetroResources_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static string CollectingText {
            get {
                return ResourceManager.GetString("CollectingText", resourceCulture);
            }
        }
        
        internal static string GroupingText {
            get {
                return ResourceManager.GetString("GroupingText", resourceCulture);
            }
        }
        
        internal static string PrioritizingText {
            get {
                return ResourceManager.GetString("PrioritizingText", resourceCulture);
            }
        }
        
        internal static string ConnectionLost {
            get {
                return ResourceManager.GetString("ConnectionLost", resourceCulture);
            }
        }
        
        internal static string Reconnect {
            get {
                return ResourceManager.GetString("Reconnect", resourceCulture);
            }
        }
        
        internal static string ConfirmMoveToDiscussing {
            get {
                return ResourceManager.GetString("ConfirmMoveToDiscussing", resourceCulture);
            }
        }
        
        internal static string DiscussingText {
            get {
                return ResourceManager.GetString("DiscussingText", resourceCulture);
            }
        }
        
        internal static string CollectingTitle {
            get {
                return ResourceManager.GetString("CollectingTitle", resourceCulture);
            }
        }
        
        internal static string GroupingTitle {
            get {
                return ResourceManager.GetString("GroupingTitle", resourceCulture);
            }
        }
        
        internal static string PrioritizingTitle {
            get {
                return ResourceManager.GetString("PrioritizingTitle", resourceCulture);
            }
        }
        
        internal static string DiscussingTitle {
            get {
                return ResourceManager.GetString("DiscussingTitle", resourceCulture);
            }
        }
        
        internal static string SlotDropText {
            get {
                return ResourceManager.GetString("SlotDropText", resourceCulture);
            }
        }
        
        internal static string NextHint {
            get {
                return ResourceManager.GetString("NextHint", resourceCulture);
            }
        }
        
        internal static string ItemRemoveConfirm {
            get {
                return ResourceManager.GetString("ItemRemoveConfirm", resourceCulture);
            }
        }
        
        internal static string PreviousHint {
            get {
                return ResourceManager.GetString("PreviousHint", resourceCulture);
            }
        }
        
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        internal static string ActionItemStageDone {
            get {
                return ResourceManager.GetString("ActionItemStageDone", resourceCulture);
            }
        }
        
        internal static string ActionItemStageNew {
            get {
                return ResourceManager.GetString("ActionItemStageNew", resourceCulture);
            }
        }
        
        internal static string TimerStart {
            get {
                return ResourceManager.GetString("TimerStart", resourceCulture);
            }
        }
        
        internal static string TimerStop {
            get {
                return ResourceManager.GetString("TimerStop", resourceCulture);
            }
        }
        
        internal static string TimerStartHint {
            get {
                return ResourceManager.GetString("TimerStartHint", resourceCulture);
            }
        }
        
        internal static string FinishHint {
            get {
                return ResourceManager.GetString("FinishHint", resourceCulture);
            }
        }
        
        internal static string GiveFacilitatorHint {
            get {
                return ResourceManager.GetString("GiveFacilitatorHint", resourceCulture);
            }
        }
        
        internal static string ConfirmGiveFacilitator {
            get {
                return ResourceManager.GetString("ConfirmGiveFacilitator", resourceCulture);
            }
        }
        
        internal static string RaiseHandHint {
            get {
                return ResourceManager.GetString("RaiseHandHint", resourceCulture);
            }
        }
        
        internal static string LowerHandHint {
            get {
                return ResourceManager.GetString("LowerHandHint", resourceCulture);
            }
        }
        
        internal static string RetroAssessmentQuestion {
            get {
                return ResourceManager.GetString("RetroAssessmentQuestion", resourceCulture);
            }
        }
        
        internal static string RetroAssessmentTitle {
            get {
                return ResourceManager.GetString("RetroAssessmentTitle", resourceCulture);
            }
        }
        
        internal static string RetroAssessmentValueHint {
            get {
                return ResourceManager.GetString("RetroAssessmentValueHint", resourceCulture);
            }
        }
        
        internal static string AssessmentSuccess {
            get {
                return ResourceManager.GetString("AssessmentSuccess", resourceCulture);
            }
        }
        
        internal static string TemplateStartStopContinue {
            get {
                return ResourceManager.GetString("TemplateStartStopContinue", resourceCulture);
            }
        }
        
        internal static string ColumnStartTitle {
            get {
                return ResourceManager.GetString("ColumnStartTitle", resourceCulture);
            }
        }
        
        internal static string ColumnStartDescription {
            get {
                return ResourceManager.GetString("ColumnStartDescription", resourceCulture);
            }
        }
        
        internal static string ColumnStopTitle {
            get {
                return ResourceManager.GetString("ColumnStopTitle", resourceCulture);
            }
        }
        
        internal static string ColumnStopDescription {
            get {
                return ResourceManager.GetString("ColumnStopDescription", resourceCulture);
            }
        }
        
        internal static string ColumnContinueDescription {
            get {
                return ResourceManager.GetString("ColumnContinueDescription", resourceCulture);
            }
        }
        
        internal static string TemplateToDiscussDiscussingDiscussed {
            get {
                return ResourceManager.GetString("TemplateToDiscussDiscussingDiscussed", resourceCulture);
            }
        }
        
        internal static string ColumnToDiscussTitle {
            get {
                return ResourceManager.GetString("ColumnToDiscussTitle", resourceCulture);
            }
        }
        
        internal static string ColumnDiscussingTitle {
            get {
                return ResourceManager.GetString("ColumnDiscussingTitle", resourceCulture);
            }
        }
        
        internal static string ColumnDiscussedTitle {
            get {
                return ResourceManager.GetString("ColumnDiscussedTitle", resourceCulture);
            }
        }
        
        internal static string ColumnContinueTitle {
            get {
                return ResourceManager.GetString("ColumnContinueTitle", resourceCulture);
            }
        }
        
        internal static string RetroPropertiesHint {
            get {
                return ResourceManager.GetString("RetroPropertiesHint", resourceCulture);
            }
        }
        
        internal static string RetroProperties {
            get {
                return ResourceManager.GetString("RetroProperties", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string VoteCountField {
            get {
                return ResourceManager.GetString("VoteCountField", resourceCulture);
            }
        }
        
        internal static string TimerDurationTemplate {
            get {
                return ResourceManager.GetString("TimerDurationTemplate", resourceCulture);
            }
        }
        
        internal static string TimerDurationField {
            get {
                return ResourceManager.GetString("TimerDurationField", resourceCulture);
            }
        }
        
        internal static string RetroTemplateField {
            get {
                return ResourceManager.GetString("RetroTemplateField", resourceCulture);
            }
        }
        
        internal static string RetroPropertiesSectionTitle {
            get {
                return ResourceManager.GetString("RetroPropertiesSectionTitle", resourceCulture);
            }
        }
        
        internal static string RetroPropertiesSectionHelp {
            get {
                return ResourceManager.GetString("RetroPropertiesSectionHelp", resourceCulture);
            }
        }
        
        internal static string RetroTypeField {
            get {
                return ResourceManager.GetString("RetroTypeField", resourceCulture);
            }
        }
        
        internal static string RetroTypeClosed {
            get {
                return ResourceManager.GetString("RetroTypeClosed", resourceCulture);
            }
        }
        
        internal static string RetroTypeHidden {
            get {
                return ResourceManager.GetString("RetroTypeHidden", resourceCulture);
            }
        }
        
        internal static string RetroTypeOpened {
            get {
                return ResourceManager.GetString("RetroTypeOpened", resourceCulture);
            }
        }
        
        internal static string ColumnToDiscussDescription {
            get {
                return ResourceManager.GetString("ColumnToDiscussDescription", resourceCulture);
            }
        }
        
        internal static string ColumnDiscussingDescription {
            get {
                return ResourceManager.GetString("ColumnDiscussingDescription", resourceCulture);
            }
        }
        
        internal static string ColumnDiscussedDescription {
            get {
                return ResourceManager.GetString("ColumnDiscussedDescription", resourceCulture);
            }
        }
        
        internal static string BacklogText {
            get {
                return ResourceManager.GetString("BacklogText", resourceCulture);
            }
        }
        
        internal static string RetroBoard {
            get {
                return ResourceManager.GetString("RetroBoard", resourceCulture);
            }
        }
        
        internal static string RetroBacklog {
            get {
                return ResourceManager.GetString("RetroBacklog", resourceCulture);
            }
        }
        
        internal static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
    }
}
