//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inc.TeamAssistant.WebUI.Features.Retro {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RetroResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RetroResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Inc.TeamAssistant.WebUI.Features.Retro.RetroResources", typeof(RetroResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static string CollectingText {
            get {
                return ResourceManager.GetString("CollectingText", resourceCulture);
            }
        }
        
        internal static string GroupingText {
            get {
                return ResourceManager.GetString("GroupingText", resourceCulture);
            }
        }
        
        internal static string PrioritizingText {
            get {
                return ResourceManager.GetString("PrioritizingText", resourceCulture);
            }
        }
        
        internal static string ConnectionLost {
            get {
                return ResourceManager.GetString("ConnectionLost", resourceCulture);
            }
        }
        
        internal static string Reconnect {
            get {
                return ResourceManager.GetString("Reconnect", resourceCulture);
            }
        }
        
        internal static string ConfirmMoveToDiscussing {
            get {
                return ResourceManager.GetString("ConfirmMoveToDiscussing", resourceCulture);
            }
        }
        
        internal static string DiscussingText {
            get {
                return ResourceManager.GetString("DiscussingText", resourceCulture);
            }
        }
        
        internal static string CollectingTitle {
            get {
                return ResourceManager.GetString("CollectingTitle", resourceCulture);
            }
        }
        
        internal static string GroupingTitle {
            get {
                return ResourceManager.GetString("GroupingTitle", resourceCulture);
            }
        }
        
        internal static string PrioritizingTitle {
            get {
                return ResourceManager.GetString("PrioritizingTitle", resourceCulture);
            }
        }
        
        internal static string DiscussingTitle {
            get {
                return ResourceManager.GetString("DiscussingTitle", resourceCulture);
            }
        }
        
        internal static string SlotDropText {
            get {
                return ResourceManager.GetString("SlotDropText", resourceCulture);
            }
        }
        
        internal static string NextHint {
            get {
                return ResourceManager.GetString("NextHint", resourceCulture);
            }
        }
        
        internal static string ItemRemoveConfirm {
            get {
                return ResourceManager.GetString("ItemRemoveConfirm", resourceCulture);
            }
        }
        
        internal static string PreviousHint {
            get {
                return ResourceManager.GetString("PreviousHint", resourceCulture);
            }
        }
        
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        internal static string ActionItemStageNew {
            get {
                return ResourceManager.GetString("ActionItemStageNew", resourceCulture);
            }
        }
        
        internal static string ActionItemStageDone {
            get {
                return ResourceManager.GetString("ActionItemStageDone", resourceCulture);
            }
        }
        
        internal static string TimerStart {
            get {
                return ResourceManager.GetString("TimerStart", resourceCulture);
            }
        }
        
        internal static string TimerStop {
            get {
                return ResourceManager.GetString("TimerStop", resourceCulture);
            }
        }
        
        internal static string TimerStartHint {
            get {
                return ResourceManager.GetString("TimerStartHint", resourceCulture);
            }
        }
        
        internal static string FinishHint {
            get {
                return ResourceManager.GetString("FinishHint", resourceCulture);
            }
        }
        
        internal static string ConfirmGiveFacilitator {
            get {
                return ResourceManager.GetString("ConfirmGiveFacilitator", resourceCulture);
            }
        }
        
        internal static string GiveFacilitatorHint {
            get {
                return ResourceManager.GetString("GiveFacilitatorHint", resourceCulture);
            }
        }
        
        internal static string RaiseHandHint {
            get {
                return ResourceManager.GetString("RaiseHandHint", resourceCulture);
            }
        }
        
        internal static string LowerHandHint {
            get {
                return ResourceManager.GetString("LowerHandHint", resourceCulture);
            }
        }
    }
}
