//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inc.TeamAssistant.WebUI.Features.Map {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MapResources_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MapResources_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Inc.TeamAssistant.WebUI.Features.Map.MapResources_ru", typeof(MapResources_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string FeatureReviewer {
            get {
                return ResourceManager.GetString("FeatureReviewer", resourceCulture);
            }
        }
        
        internal static string FeatureRandomCoffee {
            get {
                return ResourceManager.GetString("FeatureRandomCoffee", resourceCulture);
            }
        }
        
        internal static string FeatureAppraiser {
            get {
                return ResourceManager.GetString("FeatureAppraiser", resourceCulture);
            }
        }
        
        internal static string FeatureCheckIn {
            get {
                return ResourceManager.GetString("FeatureCheckIn", resourceCulture);
            }
        }
        
        internal static string RouteShow {
            get {
                return ResourceManager.GetString("RouteShow", resourceCulture);
            }
        }
        
        internal static string RouteHide {
            get {
                return ResourceManager.GetString("RouteHide", resourceCulture);
            }
        }
        
        internal static string DefaultLayerTitle {
            get {
                return ResourceManager.GetString("DefaultLayerTitle", resourceCulture);
            }
        }
    }
}
