//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inc.TeamAssistant.WebUI.Features.Constructor {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConstructorResources_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConstructorResources_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Inc.TeamAssistant.WebUI.Features.Constructor.ConstructorResources_ru", typeof(ConstructorResources_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string RemoveConfirmationText {
            get {
                return ResourceManager.GetString("RemoveConfirmationText", resourceCulture);
            }
        }
        
        internal static string NewBot {
            get {
                return ResourceManager.GetString("NewBot", resourceCulture);
            }
        }
        
        internal static string AddBot {
            get {
                return ResourceManager.GetString("AddBot", resourceCulture);
            }
        }
        
        internal static string MoveToDashboard {
            get {
                return ResourceManager.GetString("MoveToDashboard", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string SelectBotText {
            get {
                return ResourceManager.GetString("SelectBotText", resourceCulture);
            }
        }
        
        internal static string ConnectingTelegram {
            get {
                return ResourceManager.GetString("ConnectingTelegram", resourceCulture);
            }
        }
        
        internal static string MoveNextTitle {
            get {
                return ResourceManager.GetString("MoveNextTitle", resourceCulture);
            }
        }
        
        internal static string FormSectionTokenTitle {
            get {
                return ResourceManager.GetString("FormSectionTokenTitle", resourceCulture);
            }
        }
        
        internal static string FormSectionTokenHelpBegin {
            get {
                return ResourceManager.GetString("FormSectionTokenHelpBegin", resourceCulture);
            }
        }
        
        internal static string FormSectionTokenHelpEnd {
            get {
                return ResourceManager.GetString("FormSectionTokenHelpEnd", resourceCulture);
            }
        }
        
        internal static string FormSectionTokenFieldTokenLabel {
            get {
                return ResourceManager.GetString("FormSectionTokenFieldTokenLabel", resourceCulture);
            }
        }
        
        internal static string FormSectionTokenFieldUserNameLabel {
            get {
                return ResourceManager.GetString("FormSectionTokenFieldUserNameLabel", resourceCulture);
            }
        }
        
        internal static string TokenInvalid {
            get {
                return ResourceManager.GetString("TokenInvalid", resourceCulture);
            }
        }
        
        internal static string FeatureAdd {
            get {
                return ResourceManager.GetString("FeatureAdd", resourceCulture);
            }
        }
        
        internal static string FormSectionFeaturesAvailableEmptyText {
            get {
                return ResourceManager.GetString("FormSectionFeaturesAvailableEmptyText", resourceCulture);
            }
        }
        
        internal static string FeatureRemove {
            get {
                return ResourceManager.GetString("FeatureRemove", resourceCulture);
            }
        }
        
        internal static string FormSectionFeaturesSelectedEmptyText {
            get {
                return ResourceManager.GetString("FormSectionFeaturesSelectedEmptyText", resourceCulture);
            }
        }
        
        internal static string BotDetailsTelegram {
            get {
                return ResourceManager.GetString("BotDetailsTelegram", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string BotDetails {
            get {
                return ResourceManager.GetString("BotDetails", resourceCulture);
            }
        }
        
        internal static string BotDetailsHelp {
            get {
                return ResourceManager.GetString("BotDetailsHelp", resourceCulture);
            }
        }
        
        internal static string BotName {
            get {
                return ResourceManager.GetString("BotName", resourceCulture);
            }
        }
        
        internal static string BotShortDescription {
            get {
                return ResourceManager.GetString("BotShortDescription", resourceCulture);
            }
        }
        
        internal static string BotDescription {
            get {
                return ResourceManager.GetString("BotDescription", resourceCulture);
            }
        }
        
        internal static string DuplicateHolidays {
            get {
                return ResourceManager.GetString("DuplicateHolidays", resourceCulture);
            }
        }
        
        internal static string RequiredCalendar {
            get {
                return ResourceManager.GetString("RequiredCalendar", resourceCulture);
            }
        }
        
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        internal static string SupportedLanguages {
            get {
                return ResourceManager.GetString("SupportedLanguages", resourceCulture);
            }
        }
        
        internal static string SupportedLanguagesHelp {
            get {
                return ResourceManager.GetString("SupportedLanguagesHelp", resourceCulture);
            }
        }
        
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        internal static string FormSectionTokenCheckHelp {
            get {
                return ResourceManager.GetString("FormSectionTokenCheckHelp", resourceCulture);
            }
        }
        
        internal static string FeaturesStore {
            get {
                return ResourceManager.GetString("FeaturesStore", resourceCulture);
            }
        }
        
        internal static string FormSectionFeaturesCheckHelp {
            get {
                return ResourceManager.GetString("FormSectionFeaturesCheckHelp", resourceCulture);
            }
        }
        
        internal static string BooleanTrueText {
            get {
                return ResourceManager.GetString("BooleanTrueText", resourceCulture);
            }
        }
        
        internal static string BooleanFalseText {
            get {
                return ResourceManager.GetString("BooleanFalseText", resourceCulture);
            }
        }
        
        internal static string SupportedLanguagesCheck {
            get {
                return ResourceManager.GetString("SupportedLanguagesCheck", resourceCulture);
            }
        }
        
        internal static string ButtonUpdateText {
            get {
                return ResourceManager.GetString("ButtonUpdateText", resourceCulture);
            }
        }
        
        internal static string ButtonCreateText {
            get {
                return ResourceManager.GetString("ButtonCreateText", resourceCulture);
            }
        }
        
        internal static string CheckConfigurationTemplate {
            get {
                return ResourceManager.GetString("CheckConfigurationTemplate", resourceCulture);
            }
        }
        
        internal static string FormSectionFeaturesTitle {
            get {
                return ResourceManager.GetString("FormSectionFeaturesTitle", resourceCulture);
            }
        }
        
        internal static string FormSectionFeaturesHelp {
            get {
                return ResourceManager.GetString("FormSectionFeaturesHelp", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsFibonacciDescription {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsFibonacciDescription", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsTShirtDescription {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsTShirtDescription", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsPowerOfTwoDescription {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsPowerOfTwoDescription", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsAppraiserHeader {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsAppraiserHeader", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsAppraiserHelp {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsAppraiserHelp", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsStoryTypeFieldLabel {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsStoryTypeFieldLabel", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsRoundRobinDescription {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsRoundRobinDescription", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsRandomDescription {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsRandomDescription", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsReviewerHeader {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsReviewerHeader", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsReviewerHelp {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsReviewerHelp", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsNextReviewerStrategyFieldLabel {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsNextReviewerStrategyFieldLabel", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsWaitingNotificationIntervalFieldLabel {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsWaitingNotificationIntervalFieldLabel", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsInProgressNotificationIntervalFieldLabel {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsInProgressNotificationIntervalFieldLabel", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsAcceptWithCommentsFieldLabel {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsAcceptWithCommentsFieldLabel", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsNotificationInterval1Description {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsNotificationInterval1Description", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsNotificationInterval2Description {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsNotificationInterval2Description", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsNotificationInterval3Description {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsNotificationInterval3Description", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsNotificationInterval4Description {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsNotificationInterval4Description", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsRandomCoffeeHeader {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsRandomCoffeeHeader", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsRandomCoffeeHelp {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsRandomCoffeeHelp", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsRoundIntervalFieldLabel {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsRoundIntervalFieldLabel", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsVotingIntervalFieldLabel {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsVotingIntervalFieldLabel", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsRoundInterval1Description {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsRoundInterval1Description", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsRoundInterval2Description {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsRoundInterval2Description", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsRoundInterval3Description {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsRoundInterval3Description", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsRoundInterval4Description {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsRoundInterval4Description", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsVotingInterval1Description {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsVotingInterval1Description", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsVotingInterval2Description {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsVotingInterval2Description", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsVotingInterval3Description {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsVotingInterval3Description", resourceCulture);
            }
        }
        
        internal static string FormSectionSetSettingsVotingInterval4Description {
            get {
                return ResourceManager.GetString("FormSectionSetSettingsVotingInterval4Description", resourceCulture);
            }
        }
        
        internal static string WorkCalendar {
            get {
                return ResourceManager.GetString("WorkCalendar", resourceCulture);
            }
        }
        
        internal static string WorkTimeTitle {
            get {
                return ResourceManager.GetString("WorkTimeTitle", resourceCulture);
            }
        }
        
        internal static string WorkTimeHelp {
            get {
                return ResourceManager.GetString("WorkTimeHelp", resourceCulture);
            }
        }
        
        internal static string WorkAllDayLabel {
            get {
                return ResourceManager.GetString("WorkAllDayLabel", resourceCulture);
            }
        }
        
        internal static string WorkTimeStartLabel {
            get {
                return ResourceManager.GetString("WorkTimeStartLabel", resourceCulture);
            }
        }
        
        internal static string WorkTimeEndLabel {
            get {
                return ResourceManager.GetString("WorkTimeEndLabel", resourceCulture);
            }
        }
        
        internal static string WorkdaysTitle {
            get {
                return ResourceManager.GetString("WorkdaysTitle", resourceCulture);
            }
        }
        
        internal static string WorkdaysHelp {
            get {
                return ResourceManager.GetString("WorkdaysHelp", resourceCulture);
            }
        }
        
        internal static string WorkdaysLabel {
            get {
                return ResourceManager.GetString("WorkdaysLabel", resourceCulture);
            }
        }
        
        internal static string HolidaysTitle {
            get {
                return ResourceManager.GetString("HolidaysTitle", resourceCulture);
            }
        }
        
        internal static string HolidaysHelp {
            get {
                return ResourceManager.GetString("HolidaysHelp", resourceCulture);
            }
        }
        
        internal static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        internal static string WorkdayLabel {
            get {
                return ResourceManager.GetString("WorkdayLabel", resourceCulture);
            }
        }
        
        internal static string AddHolidayLabel {
            get {
                return ResourceManager.GetString("AddHolidayLabel", resourceCulture);
            }
        }
        
        internal static string DayOfWeekSunday {
            get {
                return ResourceManager.GetString("DayOfWeekSunday", resourceCulture);
            }
        }
        
        internal static string DayOfWeekMonday {
            get {
                return ResourceManager.GetString("DayOfWeekMonday", resourceCulture);
            }
        }
        
        internal static string DayOfWeekTuesday {
            get {
                return ResourceManager.GetString("DayOfWeekTuesday", resourceCulture);
            }
        }
        
        internal static string DayOfWeekWednesday {
            get {
                return ResourceManager.GetString("DayOfWeekWednesday", resourceCulture);
            }
        }
        
        internal static string DayOfWeekThursday {
            get {
                return ResourceManager.GetString("DayOfWeekThursday", resourceCulture);
            }
        }
        
        internal static string DayOfWeekFriday {
            get {
                return ResourceManager.GetString("DayOfWeekFriday", resourceCulture);
            }
        }
        
        internal static string DayOfWeekSaturday {
            get {
                return ResourceManager.GetString("DayOfWeekSaturday", resourceCulture);
            }
        }
        
        internal static string StageCheckBot {
            get {
                return ResourceManager.GetString("StageCheckBot", resourceCulture);
            }
        }
        
        internal static string StageSelectFeatures {
            get {
                return ResourceManager.GetString("StageSelectFeatures", resourceCulture);
            }
        }
        
        internal static string StageSetSettings {
            get {
                return ResourceManager.GetString("StageSetSettings", resourceCulture);
            }
        }
        
        internal static string StageComplete {
            get {
                return ResourceManager.GetString("StageComplete", resourceCulture);
            }
        }
        
        internal static string FeatureAppraiserDescription {
            get {
                return ResourceManager.GetString("FeatureAppraiserDescription", resourceCulture);
            }
        }
        
        internal static string FeatureReviewerDescription {
            get {
                return ResourceManager.GetString("FeatureReviewerDescription", resourceCulture);
            }
        }
        
        internal static string FeatureRandomCoffeeDescription {
            get {
                return ResourceManager.GetString("FeatureRandomCoffeeDescription", resourceCulture);
            }
        }
        
        internal static string FeatureCheckInDescription {
            get {
                return ResourceManager.GetString("FeatureCheckInDescription", resourceCulture);
            }
        }
        
        internal static string FeatureAppraiserName {
            get {
                return ResourceManager.GetString("FeatureAppraiserName", resourceCulture);
            }
        }
        
        internal static string FeatureReviewerName {
            get {
                return ResourceManager.GetString("FeatureReviewerName", resourceCulture);
            }
        }
        
        internal static string FeatureRandomCoffeeName {
            get {
                return ResourceManager.GetString("FeatureRandomCoffeeName", resourceCulture);
            }
        }
        
        internal static string FeatureCheckInName {
            get {
                return ResourceManager.GetString("FeatureCheckInName", resourceCulture);
            }
        }
        
        internal static string DataRefreshed {
            get {
                return ResourceManager.GetString("DataRefreshed", resourceCulture);
            }
        }
    }
}
