//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inc.TeamAssistant.WebUI.Features.Survey {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SurveyResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SurveyResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Inc.TeamAssistant.WebUI.Features.Survey.SurveyResources", typeof(SurveyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string WaitStartHealthCheck {
            get {
                return ResourceManager.GetString("WaitStartHealthCheck", resourceCulture);
            }
        }
        
        internal static string DeliveringValueTitle {
            get {
                return ResourceManager.GetString("DeliveringValueTitle", resourceCulture);
            }
        }
        
        internal static string DeliveringValueText {
            get {
                return ResourceManager.GetString("DeliveringValueText", resourceCulture);
            }
        }
        
        internal static string EasyToReleaseTitle {
            get {
                return ResourceManager.GetString("EasyToReleaseTitle", resourceCulture);
            }
        }
        
        internal static string EasyToReleaseText {
            get {
                return ResourceManager.GetString("EasyToReleaseText", resourceCulture);
            }
        }
        
        internal static string FunTitle {
            get {
                return ResourceManager.GetString("FunTitle", resourceCulture);
            }
        }
        
        internal static string FunText {
            get {
                return ResourceManager.GetString("FunText", resourceCulture);
            }
        }
        
        internal static string HealthOfCodebaseTitle {
            get {
                return ResourceManager.GetString("HealthOfCodebaseTitle", resourceCulture);
            }
        }
        
        internal static string HealthOfCodebaseText {
            get {
                return ResourceManager.GetString("HealthOfCodebaseText", resourceCulture);
            }
        }
        
        internal static string LearningTitle {
            get {
                return ResourceManager.GetString("LearningTitle", resourceCulture);
            }
        }
        
        internal static string LearningText {
            get {
                return ResourceManager.GetString("LearningText", resourceCulture);
            }
        }
        
        internal static string MissionTitle {
            get {
                return ResourceManager.GetString("MissionTitle", resourceCulture);
            }
        }
        
        internal static string MissionText {
            get {
                return ResourceManager.GetString("MissionText", resourceCulture);
            }
        }
        
        internal static string PlayerOrPawnTitle {
            get {
                return ResourceManager.GetString("PlayerOrPawnTitle", resourceCulture);
            }
        }
        
        internal static string PlayerOrPawnText {
            get {
                return ResourceManager.GetString("PlayerOrPawnText", resourceCulture);
            }
        }
        
        internal static string SpeedTitle {
            get {
                return ResourceManager.GetString("SpeedTitle", resourceCulture);
            }
        }
        
        internal static string SpeedText {
            get {
                return ResourceManager.GetString("SpeedText", resourceCulture);
            }
        }
        
        internal static string SuitableProcessesTitle {
            get {
                return ResourceManager.GetString("SuitableProcessesTitle", resourceCulture);
            }
        }
        
        internal static string SuitableProcessesText {
            get {
                return ResourceManager.GetString("SuitableProcessesText", resourceCulture);
            }
        }
        
        internal static string SupportTitle {
            get {
                return ResourceManager.GetString("SupportTitle", resourceCulture);
            }
        }
        
        internal static string SupportText {
            get {
                return ResourceManager.GetString("SupportText", resourceCulture);
            }
        }
        
        internal static string TeamworkTitle {
            get {
                return ResourceManager.GetString("TeamworkTitle", resourceCulture);
            }
        }
        
        internal static string TeamworkText {
            get {
                return ResourceManager.GetString("TeamworkText", resourceCulture);
            }
        }
    }
}
