//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inc.TeamAssistant.WebUI.Features.AssessmentSession {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AssessmentSessionResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AssessmentSessionResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Inc.TeamAssistant.WebUI.Features.AssessmentSession.AssessmentSessionResources", typeof(AssessmentSessionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MeanRating {
            get {
                return ResourceManager.GetString("MeanRating", resourceCulture);
            }
        }
        
        internal static string MedianRating {
            get {
                return ResourceManager.GetString("MedianRating", resourceCulture);
            }
        }
        
        internal static string RoundsCount {
            get {
                return ResourceManager.GetString("RoundsCount", resourceCulture);
            }
        }
        
        internal static string AcceptedValue {
            get {
                return ResourceManager.GetString("AcceptedValue", resourceCulture);
            }
        }
        
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        internal static string StoryList {
            get {
                return ResourceManager.GetString("StoryList", resourceCulture);
            }
        }
        
        internal static string AssessmentSession {
            get {
                return ResourceManager.GetString("AssessmentSession", resourceCulture);
            }
        }
        
        internal static string TaskAssess {
            get {
                return ResourceManager.GetString("TaskAssess", resourceCulture);
            }
        }
        
        internal static string AssessmentSessionAboutTemplate {
            get {
                return ResourceManager.GetString("AssessmentSessionAboutTemplate", resourceCulture);
            }
        }
        
        internal static string AssessmentSessionConnect {
            get {
                return ResourceManager.GetString("AssessmentSessionConnect", resourceCulture);
            }
        }
        
        internal static string EstimationAcceptedTemplate {
            get {
                return ResourceManager.GetString("EstimationAcceptedTemplate", resourceCulture);
            }
        }
    }
}
